### ISSUE TITLE
Design a new development FPGA

### ISSUE THREAD

**Issue by jotego** [jotego/jtframe#108]
MiSTer and Pocket are the two main FPGA platforms for retro enthusiasts. Both of them present some problems when used as a development system.

System  | Compilation | Large BRAM  | Network SD | MRA files | Extra ext RAM | Keyboard | TV out
--------|-------------|-------------|------------|-----------|---------------|----------|-------
MiSTer  | Very slow   | Yes         | Yes        | Yes       | Shared DDR    | Yes      | Yes
Pocket  | Fast        | Yes         | No         | No        | PSRAM         | No       | Dock
MiST    | Fastest     | No          | No         | No        | No            | Yes      | Yes
Ideal   | Fastest     | Yes         | Yes        | Yes       | PSRAM/DDR     | Yes      | Yes

- MiST is good for general development except when the system demands more BRAM or a frame buffer
- MiSTer is good for testing MRA files as you can change them without recompiling the RBF or extracting the SD card
- Pocket is not good for development because of lack of MRA files and keyboard

## MiSTer problems

- The DDR is unpredictable, configured in obscure ways and dependant on clocks not controlled by the clock
- The HDMI subsystem takes a large chunk of compilation time for something that's always the same. It also tends to create timing problems
- The PLL clock for the core subsystem may create problems with timing (or simply increase compilation time a lot) for certain frequencies, like when using a 6.3MHz pixel rate (~50.4MHz clock)
- SDRAM module design is hard
- For an user point of view: price and availability are not good

## Pocket problems

- Bad designed file system which tends to crash for stupid reasons (like an empty folder)
- No support for MRA files, so .rom files must be transferred
- You have to extract the SD card if you want to wipe out the core folders. Incremental changes can be done via USB, though
- No keyboard support, so debugging instructions are not possible
- Not possible to hook a serial device for communication with a PC
- No support from the manufacturer (other than free devices) and no source code available
- Tiny SRAM chip, pretty much useless

**Comment by somhi** [comment]
Some ideas for helping you develop faster and better. :)

Platforms:

* MiST compatible platform with a bigger FPGA board than MiST or SiDi. E.g. take a de10-nano and make it MiST compatible.  https://atari-forum.com/viewtopic.php?p=445410#p445410,    https://github.com/somhi/MiSTdon   (I can send you a  PCB of the MiSTdon)

* DeMiSTify platform with a bigger FPGA. No external CPU, but a synthetic CPU instead is used to aid the core for OSD options, loading rom files, HD images, arc files, ....    See current targets https://github.com/robinsonb5/DeMiSTify/tree/main/Board      Adding new targets is easy and de10-nano will be added someday soon

  Does not have all features like MiST because this platform is focussed on low FPGA resources and all the firmware is loaded in BRAM, but that could be expanded.

​		Alastair M. Robinson is at reach, and he also wants to integrate DeMiSTify someday in jtframe.   

Possible FPGAs to be used with platforms above:

* DE10-nano
* Cyclone 10 LP Refkit 10CL055  https://shop.trenz-electronic.de/en/TEI0009-02-055-8CA-Cyclone-10-LP-RefKit-10CL055-Development-Board-32-MByte-SDRAM-16-MByte-Flash   easily expandable with pmods dongles.
* QMTECH Cyclone IV 150 kLE https://es.aliexpress.com/item/1005004065727282.html
* QMTECH Cyclone V 77 kLE   (I see no stock ATM, but some people have bought it recently)

Those QMTECH will need and addon, the official one from QMTech or like those of Antonio Villena with SRAM memory.

**Comment by jotego** [comment]
I have got [one of these units](https://shop.trenz-electronic.de/en/TEI0022-03-DataStorm-DAQ-M-Board-FMC-Carrier-for-M-Series-Precision-Converters), which looks promising. I'm going to explore that option for a while.

| Feature        | MiSTer       | DataStorm         |
|:---------------|:-------------|:------------------|
| Cyclone V FPGA | 5CSEBA6U23I7 | 5CSEMA5F31 C8N    |
| Logic Elements | 110k         | 267k              |
| DSP blocks     | 360          | 1140              |
| Transceivers   | 4            | 12                |
| IO pins        | 330          | 484               |
| Memory Mbits   | 4.9          | 14.4              |
| Package        | UBGA-484     | FBGA-896          |
| DDR            | 1 (ARM)      | 1 (ARM), 1 (FPGA) |
| SDRAM          | Yes          | No                |
| Video output   | HDMI         | HDMI ADV7511      |
| USB            | Yes          | Yes x 4           |
| DIP switches   |              | 3 x 4 bits        |
| micro SD port  | Yes          | Yes               |
| Flash RAM      |              | 32 MB x 2         |
| HF connectors  | No           | Yes               |
